services: 
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: backend
    depends_on: 
      - postgres
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=todo_db;Username=postgres;Password=postgres"
    ports:
      - "8081:8081"
  frontend:
    build: ./frontend
    container_name: frontend
    depends_on: 
      - backend
    ports:
      - "8080:80"
volumes: 
  postgres_data:

      